// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./src/components/AlbumList.vue')['default']
    ArtistItem: typeof import('./src/components/ArtistItem.vue')['default']
    AudioBox: typeof import('./src/components/PlayBarTmp/AudioBox.vue')['default']
    Bar: typeof import('./src/components/PlayBarTmp/Bar.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Lyrics: typeof import('./src/components/Lyrics.vue')['default']
    MiniBar: typeof import('./src/components/PlayBarTmp/MiniBar.vue')['default']
    MvList: typeof import('./src/components/MvList.vue')['default']
    PlayBar: typeof import('./src/components/PlayBarTmp/PlayBar.vue')['default']
    PlayList: typeof import('./src/components/PlayList.vue')['default']
    ProgressLine: typeof import('./src/components/ProgressLine.vue')['default']
    Reply: typeof import('./src/components/Reply.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SongList: typeof import('./src/components/SongList.vue')['default']
  }
}

export { }
